# Generated by Django 3.1.1 on 2020-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20200914_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='category',
            field=models.CharField(choices=[('1', 'education'), ('2', 'covid')], default='education', max_length=50),
        ),
    ]
