# Generated by Django 3.1.1 on 2020-09-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_policies_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policies',
            old_name='address',
            new_name='part',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='category',
        ),
    ]
