# Generated by Django 3.1.1 on 2020-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20200915_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='category',
            field=models.CharField(choices=[('1', 'EDUCATION'), ('2', 'LABOR')], default='EDUCATION', max_length=50),
        ),
    ]
