# Generated by Django 3.1.1 on 2020-09-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20200916_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='like',
        ),
    ]